# meta-hectronic-imx

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \                                      
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hectronic-imx"
BBFILE_PATTERN_hectronic-imx = "^${LAYERDIR}/"
BBFILE_PRIORITY_hectronic-imx = "9"

LAYERDEPENDS_hectronic-imx = "core"
LAYERSERIES_COMPAT_hectronic-imx = "walnascar"
